### ISSUE TITLE
Sidebar file entries are overlapping [Ubuntu]

### ISSUE THREAD

**Issue by rahulpathakgit** [johansatge/sienna#1]
Hi,

This theme is very nice and I am facing an issue.
I am using this theme on ubuntu and I see that the sidebar file entries don't have sufficient spacing between them and they are overlapped
I have attached the screenshot
 
![screenshot from 2017-01-04 17-02-52](https://cloud.githubusercontent.com/assets/10892516/21641134/e9c653ba-d29f-11e6-8277-3b2dfc96f326.png)

Thanks
Rahul

**Comment by johansatge** [comment]
Hi,

thanks for your feedback!

I reproduce the issue on a brand new Ubuntu + Sublime install. I'll try to have a more deeper look in the next few days.

**Comment by rahulpathakgit** [comment]
I tried to fix it myself and found that changing "row_padding" in sidebar_tree changes the separation between entries. I don't know what the values mean here but changing them worked 
 "row_padding": [10, 10]

**Comment by johansatge** [comment]
The bug is caused by the `San Francisco` font which not behaves correctly on Ubuntu.

I have added a `sienna_system_font` setting in `1.1.0` (the version has been published, and should be available soon on Package Control).

Set that setting to `true` and the UI should be OK.

[Here is the diff](https://github.com/johansatge/sienna/commit/a248bc34fd3fcf070c2b441dde032215b06a4979) if you're interested.

Let me know if that helps fixing the issue!

thx
Johan

![ubuntu_ui](https://cloud.githubusercontent.com/assets/5699295/21699414/ea41564e-d39b-11e6-9c9c-88da28dc6417.png)

**Comment by rahulpathakgit** [comment]
Thanks
