### ISSUE TITLE
Arrow Icons Not showing up

### ISSUE THREAD

**Issue by tbolt** [johansatge/sienna#7]
Great theme!

The Left/Right arrow icons to handle overflow tabs and the Down arrow (in the top right) are not showing up when using this theme. 

I am on the latest Sublime Text 3 build and have a minimal amount of other plugins.
<img width="473" alt="screen shot 2018-02-07 at 9 57 18 am" src="https://user-images.githubusercontent.com/2279260/35923454-473b2a1a-0bee-11e8-87eb-33e4e2461823.png">

**Comment by johansatge** [comment]
Hi,

thanks for reporting this!

I reproduced indeed with my current Sublime version (`3134`).

The issue was a missing property on the three icons. It has been fixed in [`c5cad0b`](https://github.com/johansatge/sienna/commit/c5cad0bcd8e5ca4f79e2fba4873dd3e735bce3b8), and should be available soon in Package Control (package version `1.1.1`).

Let's close this. Feel free to reopen if you still have the issue after updating the package!

**Comment by tbolt** [comment]
Thanks Johan, really appreciate this theme.
